### ISSUE TITLE
jiggle control in sandbox setting

### ISSUE THREAD

**Issue by ebrahimebrahim** [ebrahimebrahim/knock-the-rock#49]

**Comment by ebrahimebrahim** [comment]
I'm now rethinking this. The jiggle control setup is not so easily adapted to sandbox mode. It works in challenge mode because most of the rocks on the screen are ones the player cannot interact with. If the player can interact with rocks, then jiggle control becomes very awkward for them. We can turn off jiggle control for a rock when it becomes held, but then we'd have to turn it off for nearby rocks as well, Otherwise the held rock can interact with nearby rocks as though they are static bodies, or the nearby rocks can be left floating as the held rock is removed from under them. 

If we turn off jiggle control for all rocks near a newly  held rock, then we also need to turn off jiggle control for the rocks need _those_. And so on-- basically any pile of rocks will have to have jiggle control disabled whenever any rock in that pile is touched. Is it really worth it?

Another reason I don't like it is that it's too easy to see what's going on with jiggle control in sandbox mode. In challenge mode it's not super noticeable, which is good.

**Comment by yusufmte** [comment]
Hmm, very good points. It seems like turning jiggle control on for sandbox mode would both look weird, and not take effect most of the time / when it matters most (when players make giant piles, since the non-jigglehood would just propagate through the pile as it's played with). These seem like good reasons to abandon the idea and I wouldn't mind just closing the issue based on them. Feel free to do so if you agree.
